module.exports = {
  MESSAGE: 'MESSAGE',
  MESSAGE_SAVED: 'MESSAGE_SAVED',
  GOT_MESSAGES: 'GOT_MESSAGES',

  GOT_CURRENT_USER: 'GOT_CURRENT_USER',
  GOT_USERS: 'GOT_USERS',

  FOLLOW: 'FOLLOW',
  FOLLOWED: 'FOLLOWED',

  UNFOLLOW: 'UNFOLLOW',
  UNFOLLOWED: 'UNFOLLOWED'
};
